try:
	print(x)
except:
	print("Somethingnwent wrong")
finally:
	print("The try except is finished")
